### ISSUE TITLE
如何支持 less ？

### ISSUE THREAD

**Issue by telen** [sorrycc/dva-boilerplate-isomorphic#4]
将 App.css 改成 App.less ，增加 webpack less-loader 报错？

```
SyntaxError: /Users/user/dva-boilerplate-isomorphic-master/common/routes/App.less: Unexpected token (2:0)
    1 |
> 2 | .title {
      | ^
  3 |   color: red;
  4 | }
  5 |
    at Parser.pp$5.raise (/Users/user/dva-boilerplate-isomorphic-master/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/Users/user/dva-boilerplate-isomorphic-master/node_modules/babylon/lib/index.js:1705:8)
```

**Comment by sorrycc** [comment]
看出错信息是被当成 js 解析了。

**Comment by telen** [comment]
问题出在启动的时候，因为启动后再修改 `import styles from './App.css';` 为 `import styles from './App.less';` 是能够正常编译的。

所以怎么让 server 启动时编译也能支持呢？

**Comment by telen** [comment]
找到了原因， `css-modules-require-hook` 默认似乎只处理 css 后缀文件，增加一个就可以了。
```
require('css-modules-require-hook')({
  generateScopedName: '[local]___[hash:base64:5]',
  extensions: ['.css', '.less']
});
```
